import { SITE_CONFIG } from './config.js';
const $=(s,r=document)=>r.querySelector(s); const grid=$('#writeupGrid'); const overlay=$('#writeupOverlay'); let articles=[];
const escapeHTML=s=>String(s||'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function cleanText(s=''){ const d=document.createElement('div'); d.innerHTML=s; return d.textContent.replace(/\s+/g,' ').trim(); }
function textFromHtml(html=''){ const d=document.createElement('div'); d.innerHTML=html; return d.textContent.replace(/\s+/g,' ').trim(); }
function render(){ if(!articles.length){grid.innerHTML='<div class="empty-card"><div class="kicker">No feed yet</div><h3>Connect your Medium username</h3><p class="muted">Open js/config.js and set MEDIUM_USERNAME to your real Medium handle.</p></div>';return;} grid.innerHTML=articles.map((a,i)=>`<article class="writeup-card reveal" tabindex="0" data-index="${i}"><div class="writeup-image">${a.thumbnail?`<img src="${escapeHTML(a.thumbnail)}" alt="">`:''}<span>${String(i+1).padStart(2,'0')}</span></div><div class="writeup-copy"><div class="writeup-meta"><span>${escapeHTML(new Date(a.pubDate).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}))}</span><span>${Math.max(1,Math.round(textFromHtml(a.description).split(/\s+/).length/200))} min read</span></div><h3>${escapeHTML(a.title)}</h3><p>${escapeHTML(textFromHtml(a.description).slice(0,190))}…</p><span class="read-arrow">Open preview ↗</span></div></article>`).join(''); document.querySelectorAll('.writeup-card').forEach(c=>{c.addEventListener('click',()=>open(+c.dataset.index));c.addEventListener('keydown',e=>e.key==='Enter'&&open(+c.dataset.index));});}
function open(i){const a=articles[i]; $('#writeupDetailTitle').textContent=a.title; $('#writeupDetailMeta').textContent=`${new Date(a.pubDate).toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})} · ${a.author||'Medium'}`; const body=cleanText(textFromHtml(a.description)); $('#writeupDetailBody').innerHTML=`<p>${escapeHTML(body)}</p><div class="reading-note">This is the live Medium preview. Use the button below to continue reading the complete article on Medium.</div>`; $('#writeupDetailLink').href=a.link||SITE_CONFIG.FALLBACK_MEDIUM_URL; overlay.classList.add('open'); overlay.setAttribute('aria-hidden','false'); document.body.style.overflow='hidden'; }
function close(){overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');document.body.style.overflow='';}
async function load(){grid.innerHTML='<div class="loading-card"><span class="spinner"></span><p>Loading Medium previews…</p></div>'; const username=SITE_CONFIG.MEDIUM_USERNAME.trim(); if(!username){render();return;} const rss=`https://medium.com/feed/${encodeURIComponent(username)}`; $('#mediumSourceText').textContent=`medium.com/@${username}`; try{const res=await fetch(`${SITE_CONFIG.MEDIUM_API}${encodeURIComponent(rss)}`); const data=await res.json(); articles=data.items||[]; render(); document.querySelectorAll('.reveal').forEach(e=>{if(!e.classList.contains('visible')) e.classList.add('visible')});}catch(err){grid.innerHTML='<div class="empty-card"><div class="kicker">Feed unavailable</div><h3>Medium could not be loaded in the browser.</h3><p class="muted">The page is wired correctly, but the external RSS bridge may be unavailable. The portfolio remains usable and you can switch the feed source in js/config.js.</p></div>';}}
$('#mediumRefresh')?.addEventListener('click',load); overlay?.addEventListener('click',e=>{if(e.target===overlay)close()}); $$('[data-close]',overlay).forEach(b=>b.addEventListener('click',close)); document.addEventListener('keydown',e=>e.key==='Escape'&&close()); load();
